<?php

namespace App\Enums;

class ErrorCodes {
    //ACADEMIES (1XXX)
    const ACADEMY_DELETE_ERROR = 131;
    const ACADEMY_UPDATE_ERROR = 121;
    const ACADEMY_CREATE_ERROR = 111;

    //INSCRIPTIONS (2XXX)
    const INSCRIPTION_DELETE_ERROR = 231;
    const INSCRIPTION_UPDATE_ERROR = 221;
    const INSCRIPTION_CREATE_ERROR = 211;

    //LESSONS (3XXX)
    const LESSON_DELETE_ERROR = 331;
    const LESSON_ACTIVE_ERROR = 341;
    const LESSON_UPDATE_ERROR = 321;
    const LESSON_CREATE_ERROR = 311;
    const LESSON_OTHER_ERROR = 351;

    //PAYMENTS (5XXX)
    const PAYMENT_DELETE_ERROR = 531;
    const PAYMENT_UPDATE_ERROR = 521;
    const PAYMENT_CREATE_ERROR = 511;

    //PERMISSIONS (6XXX)
    const PERMISSION_DELETE_ERROR = 631;
    const PERMISSION_UPDATE_ERROR = 621;
    const PERMISSION_CREATE_ERROR = 611;

    //ROLES (7XXX)
    const ROLE_DELETE_ERROR = 731;
    const ROLE_UPDATE_ERROR = 721;
    const ROLE_CREATE_ERROR = 711;

    //SCHEDULES (8XX)
    const SCHEDULE_UPDATE_ERROR = 821;
    const SCHEDULE_OTHER_ERROR = 851;
    const SCHEDULE_DELETE_ERROR = 831;

    //STUDENTS (9XXX)
    const STUDENT_DELETE_ERROR = 931;
    const STUDENT_ACTIVE_ERROR = 941;
    const STUDENT_UPDATE_ERROR = 931;
    const STUDENT_CREATE_ERROR = 911;

    //TEACHERS (10XX)
    const TEACHER_DELETE_ERROR = 1011;
    const TEACHER_UPDATE_ERROR = 1021;
    const TEACHER_CREATE_ERROR = 1011;
    const TEACHER_OTHER_ERROR  = 1051;
    const TEACHER_OTHER_ERROR_2 = 1052;

    //USERS (11XX)
    const USER_DELETE_ERROR = 1131;
    const USER_UPDATE_ERROR = 1121;
    const USER_CREATE_ERROR = 1111;
}